version: '3'

services:
  nginx:
    image: nginx:1.13
    container_name: nginx
    ports:
      - '0.0.0.0:80:80'
      - '0.0.0.0:443:443'
    volumes:
      - ./src:/var/www/html
      - ./docker/nginx/nginx.conf:/etc/nginx/nginx.conf
      - ./docker/ssl:/etc/ssl
      - ./docker/log/nginx:/var/log/nginx
    depends_on:
      - apache
    restart: always

  apache:
    image: httpd:2.4
    container_name: apache
    volumes:
      - ./src:/var/www/html
      - ./docker/httpd/httpd.conf:/usr/local/apache2/conf/httpd.conf
      - ./docker/log/httpd:/var/log/apache2
    depends_on:
      - php
    restart: always

  php:
    build: ./docker/php71
    container_name: php
    volumes:
      - ./src:/var/www/html
      - ./docker/php71/php.ini:/usr/local/etc/php/conf.d/php71.ini
      - ./docker/log/php:/var/log/php
    depends_on:
      - db
    restart: always

  db:
    image: mysql:5.7
    container_name: db
    ports:
        - '0.0.0.0:3306:3306'
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: dev
      MYSQL_USER: dev
      MYSQL_PASSWORD: dev
    volumes:
      - ./docker/mysql/my.cnf:/etc/mysql/conf.d/my.cnf
      - ./docker/data/mysql:/var/lib/mysql
      - ./docker/log/mysql:/var/log/mysql
    restart: always

  phpmyadmin:
    image: phpmyadmin/phpmyadmin
    container_name: phpmyadmin
    ports:
     - 8080:80
    environment:
      MYSQL_ROOT_PASSWORD: root
    depends_on:
      - db
    restart: always

  memcached:
    image: memcached:1.5
    container_name: memcached
    volumes:
      - ./docker/log/memcached:/var/log/memcached
      - ./docker/data/memcached:/var/lib/memcached
    ports:
      - '0.0.0.0:11211:11211'